apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-ui-gh-runner-deployment-hpa
  labels:
    app: runner
spec:
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.autoscaling.resource.type }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.resource.targetAverageUtilization }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-ui-gh-runner-deployment
