apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-ui-gh-runner-deployment-hpa
  labels:
    app: runner
spec:
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - resource:
      name: {{ .Values.autoscaling.resource.type }}
      targetAverageUtilization: {{ .Values.autoscaling.resource.targetAverageUtilization }}
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-ui-gh-runner-deployment
