apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-ui-gh-runners-hpa
  labels:
    app: runner
spec:
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 25
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-ui-gh-runners
