autoscaling:
  minReplicas: 2
  maxReplicas: 12
  resource:
    type: cpu
    targetAverageUtilization: 25

resources: 
  limits:
    memory: "10Gi"
    cpu: "6"
  requests:
    memory: "8Gi"
    cpu: "4"

runner:
  image:
    repository: $DOCKER_REGISTRY/$DOCKER_IMAGE
    tag: $IMAGE_VERSION
    pullPolicy: Always
  githubSecret:
    name: web-ui-gh-runner-secret
    token: $GITHUB_ACCESS_TOKEN

probes:
  readiness:
    initialDelaySeconds: 15
    periodSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 2
    command:
      - pgrep
      - -f
      - Runner.Listener

  liveness:
    initialDelaySeconds: 30
    periodSeconds: 20
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 2
    command:
      - pgrep
      - -f
      - Runner.Listener
