autoscaling:
  minReplicas: 2
  maxReplicas: 6
  resource:
    type: cpu
    targetAverageUtilization: 25

resources: 
  limits:
    memory: "4Gi"
    cpu: "4"
  requests:
    memory: "3Gi"
    cpu: "3"

runner:
  image:
    repository: $DOCKER_REGISTRY/$DOCKER_IMAGE
    tag: $IMAGE_VERSION
    pullPolicy: Always
  githubSecret:
    name: web-ui-gh-runner-secret
    token: $GITHUB_ACCESS_TOKEN
