name: Build

on:
  push:
    branches: [ master ]
  pull_request: 
    types: [ opened, synchronize, reopened, labeled ]
    branches: 
      - master
  schedule:
    - cron: '0 0 * * 0'  # every week at midnight on sunday

env:
  DOCKER_REGISTRY: us-east1-docker.pkg.dev
  IMAGE_VERSION: latest
  DOCKER_IMAGE: ${{ secrets.GKE_PROJECT }}/webui/gh-runner
  GKE_CLUSTER: jx-prod
  GKE_ZONE: us-east1-b
  RUNNER_NAMESPACE: webui
  GITHUB_ACTIONS_SECRET_KEY: web-ui-gh-runner-secret

jobs:
  runner-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup nuxeo yam repository
        run: |
          echo -e "[nuxeo]\nname=Nexus Private Yum Release Repository\nbaseurl=https://packages.nuxeo.com/repository/yum-registry/\nusername=${{ secrets.YUM_REPO_USERNAME }}\npassword=${{ secrets.YUM_REPO_PASSWORD }}\nenabled=1\ngpgcheck=0" > nuxeo.repo

      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GKE_SA_KEY }}
          push: true
          repository: ${{ secrets.GKE_PROJECT }}/webui/gh-runner
          tags: ${{ env.IMAGE_VERSION }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ secrets.GKE_PROJECT }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Check runner namespace
        id: runner_ns
        run: |
          echo ::set-output name=exists::$(kubectl get namespace ${RUNNER_NAMESPACE})

      - name: Create runner namespace
        if: ${{ !steps.runner_ns.outputs.exists }}
        run: |
          kubectl create namespace ${{ env.RUNNER_NAMESPACE }}

      - name: Check github actions secret
        id: gh_secret
        run: |
          echo ::set-output name=exists::$(kubectl get secret ${GITHUB_ACTIONS_SECRET_KEY} --namespace ${RUNNER_NAMESPACE})

      - name: Create github actions secret
        if: ${{ !steps.gh_secret.outputs.exists }}
        run: |
          # create the necessary secret to register the runner in nuxeo-web-ui repository
          kubectl create secret generic ${{ env.GITHUB_ACTIONS_SECRET_KEY }} --from-literal=GITHUB_TOKEN=${{ secrets.ACCESS_TOKEN }} --namespace ${{ env.RUNNER_NAMESPACE }}

      # testing this before creating a helm chart
      - name: Install runner image
        id: runner
        working-directory: ./charts/runner
        run: |
          # install Helm
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash -

          # update helm deps
          helm dependency update .

          # install
          helm upgrade --install --namespace ${RUNNER_NAMESPACE} ${RUNNER_NAMESPACE} .
