name: Build

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GKE_SA_KEY:
        description: 'GKE_SA_KEY'
        required: true
      GKE_PROJECT:
        description: 'GKE_PROJECT'
        required: true

env:
  DOCKER_REGISTRY: us-east1-docker.pkg.dev
  IMAGE_VERSION: latest
  DOCKER_IMAGE: ${{ secrets.GKE_PROJECT }}/webui/gh-runner

jobs:
  build-runner-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GKE_SA_KEY }}
          push: true
          repository: ${{ env.DOCKER_IMAGE }}
          tags: ${{ env.IMAGE_VERSION }}
