name: Build and deploy runner image to k8s cluster

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'  # every week at midnight on sunday
  workflow_dispatch:

env:
  DOCKER_REGISTRY: us-east1-docker.pkg.dev
  IMAGE_VERSION: latest
  DOCKER_IMAGE: ${{ secrets.GKE_PROJECT }}/webui/gh-runner
  GKE_CLUSTER: jx-prod
  GKE_ZONE: us-east1-b
  RUNNER_NAMESPACE: webui
  GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  build-runner-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GKE_SA_KEY }}
          push: true
          repository: ${{ env.DOCKER_IMAGE }}
          tags: ${{ env.IMAGE_VERSION }}

  deploy-runner-image:
    uses: .github/workflows/deploy.yaml@master
