name: Build and deploy

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'  # every week at midnight on sunday
  workflow_dispatch:

jobs:
  build:
    uses: nuxeo/nuxeo-web-ui-gh-runner/.github/workflows/build.yaml@master
    secrets:
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  deploy:
    needs: build
    uses: nuxeo/nuxeo-web-ui-gh-runner/.github/workflows/deploy.yaml@master
    secrets:
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
